name: Build llama for macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure
      run: |
        mkdir build
        cd build
        cmake .. -DLLAMA_BUILD_EXAMPLES=ON

    - name: Build llama
      run: |
        cd build
        cmake --build . --target llama --config Release

    - name: Upload llama binary
      uses: actions/upload-artifact@v4
      with:
        name: llama-macos
        path: build/bin/llama
