name: Build main for macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: brew install cmake

    - name: Configure
      run: |
        mkdir build
        cd build
        cmake .. -DLLAMA_BUILD_EXAMPLES=ON

    - name: Build 'main' only
      run: |
        cd build
        cmake --build . --target main --config Release

    - name: Upload main binary
      uses: actions/upload-artifact@v4
      with:
        name: main-macos
        path: build/bin/main
